runtime: python27
api_version: 1
threadsafe: true

default_expiration: "3d"

handlers:
    
- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html
  
- url: /video/(.*\.webm)
  static_files: static/video/\1
  mime_type: video/webm
  upload: video/

- url: /
  static_dir: static

